version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT:-5000}:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5000

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://backend:${BACKEND_PORT:-5000}
    depends_on:
      - backend
